// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID        uuid.UUID
	OrgID     uuid.NullUUID
	AppGrpID  uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AppGroup struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	Name      string
	Scopes    []string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID         uuid.UUID
	Email      string
	Password   string
	AppGroupID uuid.UUID
	OrgID      uuid.NullUUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
