// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	AppGrpID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AppGroup struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	Name      string
	Scopes    []string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID         pgtype.UUID
	Email      string
	Password   string
	AppGroupID pgtype.UUID
	OrgID      pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
