// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createApp = `-- name: CreateApp :one
INSERT INTO apps (org_id, app_grp_id)
VALUES ($1, $2)
RETURNING id, org_id, app_grp_id, created_at, updated_at
`

type CreateAppParams struct {
	OrgID    uuid.NullUUID
	AppGrpID uuid.UUID
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createApp, arg.OrgID, arg.AppGrpID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppGrpID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAppGroup = `-- name: CreateAppGroup :one
INSERT INTO app_groups (org_id, name, scopes)
VALUES ($1, $2, $3)
RETURNING id, org_id, name, scopes, created_at, updated_at
`

type CreateAppGroupParams struct {
	OrgID  uuid.UUID
	Name   string
	Scopes []string
}

func (q *Queries) CreateAppGroup(ctx context.Context, arg CreateAppGroupParams) (AppGroup, error) {
	row := q.db.QueryRow(ctx, createAppGroup, arg.OrgID, arg.Name, arg.Scopes)
	var i AppGroup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password, app_group_id, org_id)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password, app_group_id, org_id, created_at, updated_at
`

type CreateUserParams struct {
	Email      string
	Password   string
	AppGroupID uuid.UUID
	OrgID      uuid.NullUUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Password,
		arg.AppGroupID,
		arg.OrgID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.AppGroupID,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAndAppGrpByEmail = `-- name: GetUserAndAppGrpByEmail :one
SELECT users.id, users.email, users.password, users.app_group_id, users.org_id, users.created_at, users.updated_at, app_groups.scopes
FROM users
JOIN app_groups ON users.app_group_id = app_groups.id WHERE email = $1
`

type GetUserAndAppGrpByEmailRow struct {
	ID         uuid.UUID
	Email      string
	Password   string
	AppGroupID uuid.UUID
	OrgID      uuid.NullUUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	Scopes     []string
}

func (q *Queries) GetUserAndAppGrpByEmail(ctx context.Context, email string) (GetUserAndAppGrpByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserAndAppGrpByEmail, email)
	var i GetUserAndAppGrpByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.AppGroupID,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scopes,
	)
	return i, err
}
