// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createApp = `-- name: CreateApp :one
INSERT INTO apps (org_id, app_grp_id)
VALUES ($1, $2)
RETURNING id, org_id, app_grp_id, created_at, updated_at
`

type CreateAppParams struct {
	OrgID    uuid.NullUUID
	AppGrpID uuid.UUID
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createApp, arg.OrgID, arg.AppGrpID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppGrpID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAppGroup = `-- name: CreateAppGroup :one
INSERT INTO app_groups (org_id, name, scopes)
VALUES ($1, $2, $3)
RETURNING id, org_id, name, scopes, created_at, updated_at
`

type CreateAppGroupParams struct {
	OrgID  uuid.UUID
	Name   string
	Scopes []string
}

func (q *Queries) CreateAppGroup(ctx context.Context, arg CreateAppGroupParams) (AppGroup, error) {
	row := q.db.QueryRow(ctx, createAppGroup, arg.OrgID, arg.Name, arg.Scopes)
	var i AppGroup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password, app_group_id, org_id)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password, app_group_id, org_id, created_at, updated_at
`

type CreateUserParams struct {
	Email      string
	Password   string
	AppGroupID uuid.UUID
	OrgID      uuid.NullUUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Password,
		arg.AppGroupID,
		arg.OrgID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.AppGroupID,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dbCleanUp = `-- name: DbCleanUp :exec
DROP TABLE IF EXISTS apps, app_groups, users, schema_migrations CASCADE
`

func (q *Queries) DbCleanUp(ctx context.Context) error {
	_, err := q.db.Exec(ctx, dbCleanUp)
	return err
}

const getAppGroupByID = `-- name: GetAppGroupByID :one
SELECT id, org_id, name, scopes, created_at, updated_at
FROM app_groups
WHERE id = $1
`

func (q *Queries) GetAppGroupByID(ctx context.Context, id uuid.UUID) (AppGroup, error) {
	row := q.db.QueryRow(ctx, getAppGroupByID, id)
	var i AppGroup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppGroupByName = `-- name: GetAppGroupByName :one
SELECT id, org_id, name, scopes, created_at, updated_at
FROM app_groups
WHERE name = $1
`

func (q *Queries) GetAppGroupByName(ctx context.Context, name string) (AppGroup, error) {
	row := q.db.QueryRow(ctx, getAppGroupByName, name)
	var i AppGroup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppGrpByAppID = `-- name: GetAppGrpByAppID :one
SELECT app_groups.id, app_groups.org_id, name, scopes, app_groups.created_at, app_groups.updated_at, apps.id, apps.org_id, app_grp_id, apps.created_at, apps.updated_at from app_groups JOIN apps on app_groups.id = apps.app_grp_id WHERE apps.id = $1
`

type GetAppGrpByAppIDRow struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	Name        string
	Scopes      []string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ID_2        uuid.UUID
	OrgID_2     uuid.NullUUID
	AppGrpID    uuid.UUID
	CreatedAt_2 pgtype.Timestamptz
	UpdatedAt_2 pgtype.Timestamptz
}

func (q *Queries) GetAppGrpByAppID(ctx context.Context, id uuid.UUID) (GetAppGrpByAppIDRow, error) {
	row := q.db.QueryRow(ctx, getAppGrpByAppID, id)
	var i GetAppGrpByAppIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.OrgID_2,
		&i.AppGrpID,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
	)
	return i, err
}

const getUserAndAppGrpByEmail = `-- name: GetUserAndAppGrpByEmail :one
SELECT users.id, users.email, users.password, users.app_group_id, users.org_id, users.created_at, users.updated_at, app_groups.scopes
FROM users
JOIN app_groups ON users.app_group_id = app_groups.id WHERE email = $1
`

type GetUserAndAppGrpByEmailRow struct {
	ID         uuid.UUID
	Email      string
	Password   string
	AppGroupID uuid.UUID
	OrgID      uuid.NullUUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	Scopes     []string
}

func (q *Queries) GetUserAndAppGrpByEmail(ctx context.Context, email string) (GetUserAndAppGrpByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserAndAppGrpByEmail, email)
	var i GetUserAndAppGrpByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.AppGroupID,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scopes,
	)
	return i, err
}

const updateAppGroup = `-- name: UpdateAppGroup :one
UPDATE app_groups
SET name = $2,
    scopes = $3,
    org_id = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, name, scopes, created_at, updated_at
`

type UpdateAppGroupParams struct {
	ID     uuid.UUID
	Name   string
	Scopes []string
	OrgID  uuid.UUID
}

func (q *Queries) UpdateAppGroup(ctx context.Context, arg UpdateAppGroupParams) (AppGroup, error) {
	row := q.db.QueryRow(ctx, updateAppGroup,
		arg.ID,
		arg.Name,
		arg.Scopes,
		arg.OrgID,
	)
	var i AppGroup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
